[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Directories=16x16/apps,48x48/apps,64x64/apps,128x128/apps,256x256/apps,scalable/apps,symbolic/apps

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[64x64/apps]
Size=64
Context=Applications
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[scalable/apps]
Size=128
MinSize=1
MaxSize=512
Context=Applications
Type=Scalable

[symbolic/apps]
Size=16
MinSize=8
MaxSize=512
Context=Applications
Type=Scalable
